Added testing H5Z-ZFP with Fortran.

diff --git a/test/Makefile b/test/Makefile
--- a/test/Makefile
+++ b/test/Makefile
@@ -12,6 +12,13 @@ include ../config.make
 TEST_SRC = test_write.c test_read.c
 TEST_OBJ = $(TEST_SRC:.c=.o)
 
+EXEC = test_write test_read
+ifneq ($(FC),)
+EXEC += test_rw_fortran
+TEST_OBJ += H5Zzfc.o test_rw_fortran.o
+FTESTS = test-rate-f test-precision-f test-accuracy-f
+endif
+
 help:
 	@echo "               This is H5Z-ZFP version $(H5Z_ZFP_VERSINFO)."
 	@echo "           See README file for detailed information."
@@ -22,6 +29,7 @@ help:
 	@echo ""
 	@echo "where 'path' is a dir whose children are inc/lib/bin subdirs."
 	@echo "Other variables (e.g. CFLAGS, LD, etc.) can be set as usual."
+	@echo "Optionally, add FC=<fortran-compiler> to include Fortran tests."
 	@echo ""
 	@echo "Available make targets are..."
 	@echo "    test_write - build just the write test for zfp"
@@ -30,6 +38,10 @@ help:
 	@echo "    test-accuracy - run ZFP accuracy mode tests"
 	@echo "    test-precision - run ZFP precision mode tests"
 	@echo "    test-h5repack - run ZFP using HDF5's h5repack (requires patch to h5repack)"
+	@echo "    test_rw_fortran - Fortran write read test for zfp"
+	@echo "    test-rate-f  - run Fortran ZFP rate mode tests"
+	@echo "    test-accuracy-f - run Fortran ZFP accuracy mode tests"
+	@echo "    test-precision-f - run Fortran ZFP precision mode tests"
 	@echo "    all - run all tests"
 	@echo "    clean - clean everything"
 
@@ -50,11 +62,63 @@ test_write: test_write.o props
 test_read: test_read.o plugin
 	$(CC) $< -o $@ $(PREPATH)$(HDF5_LIB) -L$(HDF5_LIB) $(LDFLAGS)
 
+ifneq ($(FC),)
+
+test_rw_fortran: H5Zzfc.o test_rw_fortran.o
+	$(FC) $(FCFLAGS) -o $@ $^ $(PREPATH)$(HDF5_LIB) ../src/props/H5Zzfp_props.o -L$(HDF5_LIB) $(LDFLAGS) -lhdf5_fortran
+	env HDF5_PLUGIN_PATH=$(H5Z_ZFP_PLUGIN) ./test_rw_fortran
+
+%.o:%.F90
+	$(FC)  -o $@ -c $< $(FCFLAGS) -I$(H5Z_ZFP_BASE) -I$(ZFP_INC) -I$(HDF5_INC)
+
+
+# Decrease bit rate and confirm compression ratio increases
+test-rate-f: plugin test_rw_fortran 
+	@for r in 32 16 8 4; do\
+	    expected_ratio=$$(expr 64 \/ $$r); \
+	    env HDF5_PLUGIN_PATH=$(H5Z_ZFP_PLUGIN) ./test_rw_fortran zfpmode 1 rate $$r 2>&1 1>/dev/null; \
+	    actual_ratio=$$(env LD_LIBRARY_PATH=$(HDF5_LIB) HDF5_PLUGIN_PATH=$(H5Z_ZFP_PLUGIN) $(HDF5_BIN)/h5dump -H -d compressed -p test_zfp.h5 | grep COMPRESSION | cut -d':' -f1 | cut -d'(' -f2 | cut -d'.' -f1); \
+	    if [[ $$expected_ratio -ne $$actual_ratio ]]; then \
+	        echo "Fortran ZFP rate test failed for rate=$$r"; \
+	        exit 1; \
+	    fi; \
+	done; \
+	echo "Fortran Rate tests Passed"
+
+# Increase accuracy and test absolute error tolerance is within accuracy
+test-accuracy-f: plugin test_rw_fortran
+	@for a in 0.1 0.01 0.001 0.0001; do\
+	    env HDF5_PLUGIN_PATH=$(H5Z_ZFP_PLUGIN) ./test_rw_fortran zfpmode 3 acc $$a write_only 2>&1 1>/dev/null; \
+	    env LD_LIBRARY_PATH=$(HDF5_LIB) HDF5_PLUGIN_PATH=$(H5Z_ZFP_PLUGIN) $(HDF5_BIN)/h5diff -v -d $$a test_zfp.h5 test_zfp.h5 compressed original 2>&1 1>/dev/null; \
+	    if [[ $$? -ne 0 ]]; then \
+	        echo "Fortran ZFP accuracy test failed for accuracy=$$a"; \
+	        exit 1; \
+	    fi; \
+	done; \
+	echo "Fortran Accuracy tests Passed"
+
+# Increase precision and confirm diff count for given tolerance drops
+test-precision-f: plugin test_rw_fortran
+	@ldiffcnt=0; \
+	for p in 12 16 20 24; do\
+	    env HDF5_PLUGIN_PATH=$(H5Z_ZFP_PLUGIN) ./test_rw_fortran zfpmode 2 prec $$p write_only 2>&1 1>/dev/null; \
+	    diffcnt=$$(env LD_LIBRARY_PATH=$(HDF5_LIB) HDF5_PLUGIN_PATH=$(H5Z_ZFP_PLUGIN) $(HDF5_BIN)/h5diff -v -p 0.00001 test_zfp.h5 test_zfp.h5 compressed original | grep 'differences found' | cut -d' ' -f1); \
+	    if [[ $$ldiffcnt -ne 0 ]] && [[ $$diffcnt -gt $$ldiffcnt ]]; then \
+	        echo "Fortran ZFP precision test failed for precision=$$p"; \
+		exit 1; \
+	    fi; \
+	    ldiffcnt=$$diffcnt; \
+	done; \
+	echo "Fortran Precision tests Passed"
+
+
+endif
+
 # Decrease bit rate and confirm compression ratio increases
 test-rate: plugin test_write
 	@for r in 32 16 8 4; do\
 	    expected_ratio=$$(expr 64 \/ $$r); \
-	    env HDF5_PLUGIN_PATH=$(H5Z_ZFP_PLUGIN) ./test_write zfpmode=1 rate=$$r 2>&1 1>/dev/null; \
+	    env HDF5_PLUGIN_PATH=$(H5Z_ZFP_PLUGIN) ./test_write zfpmode=1 rate=$$r write_only 2>&1 1>/dev/null; \
 	    actual_ratio=$$(env LD_LIBRARY_PATH=$(HDF5_LIB) HDF5_PLUGIN_PATH=$(H5Z_ZFP_PLUGIN) $(HDF5_BIN)/h5dump -H -d compressed -p test_zfp.h5 | grep COMPRESSION | cut -d':' -f1 | cut -d'(' -f2 | cut -d'.' -f1); \
 	    if [[ $$expected_ratio -ne $$actual_ratio ]]; then \
 	        echo "ZFP rate test failed for rate=$$r"; \
@@ -136,8 +200,8 @@ test-endian: plugin test_zfp_le.h5 test_zfp_be.h5
 	fi; \
 	echo "Endian test Passed"
 
-check: test_write test_read test-rate test-precision test-accuracy test-endian
+check: $(EXEC) $(FTESTS) test-rate test-precision test-accuracy test-endian 
 
 clean:
-	@versinfo=$$(grep '#define H5Z_FILTER_ZFP_VERSION_[MP]' H5Zzfp.h | cut -d' ' -f3 | tr '\n' '.' | cut -d'.' -f-3); \
-	rm -f $(TEST_OBJ) $(PROP_OBJ) test_zfp.h5 mesh_repack.h5 test_write test_read
+	@versinfo=$$(grep '#define H5Z_FILTER_ZFP_VERSION_[MP]' $(H5Z_ZFP_BASE)/H5Zzfp.h | cut -d' ' -f3 | tr '\n' '.' | cut -d'.' -f-3); \
+	rm -f $(TEST_OBJ) $(PROP_OBJ) test_zfp.h5 mesh_repack.h5 $(EXEC) *.mod
